name: SiT
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision
  - git
  - pip
  - diffusers
  - timm
  - torchdiffeq
